const $ = selector => document.querySelector(selector);
const storageKey = 'acerto-motorista-final-v1';
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const defaultFields = () => ({ frota:'', motorista:'', origem:'', cidadeDestino:'', ufDestino:'', valorFrete:'', dataSaida:'', dataRetorno:'', kmSaida:'', kmChegada:'', adiantamentoCartao:'', adiantamentoDinheiro:'', observacao:'' });
let state = JSON.parse(localStorage.getItem(storageKey) || 'null') || { active: [], history: [], account: { empresa:'', responsavel:'' } };
let ui = { screen: 'fleets', currentId: null, step: 1, historyFilter: '', newFleet: false, closingName: '', tripTab: 'fuel' };

function save() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function esc(value='') { return String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
function createId() { return globalThis.crypto?.randomUUID?.() || `frota-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function number(value) { return Number(String(value || '').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'')) || 0; }
function brl(value) { return money.format(value); }
function currencyMask(value) { const digits = String(value || '').replace(/\D/g,''); return digits ? (Number(digits)/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}) : ''; }
function dateText(value) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : 'Não informado'; }
function current() { return state.active.find(item => item.id === ui.currentId); }
function totals(record) { const fuel = record.fueling.reduce((sum,item) => sum + number(item.amount),0); const extras = record.extras.reduce((sum,item) => sum + number(item.amount),0); const advances = number(record.fields.adiantamentoCartao) + number(record.fields.adiantamentoDinheiro); const freight = number(record.fields.valorFrete); return { fuel, extras, expenses:fuel+extras, advances, freight, net:freight+advances-fuel-extras }; }
function touch(record) { record.updatedAt = new Date().toISOString(); save(); }
function nav() { document.querySelectorAll('[data-nav]').forEach(button => button.classList.toggle('active', button.dataset.nav === ui.screen)); }
function render() { const view = $('#view'); if (ui.screen === 'fleets') view.innerHTML = fleetsView(); if (ui.screen === 'history') view.innerHTML = historyView(); if (ui.screen === 'account') view.innerHTML = accountView(); if (ui.screen === 'wizard') view.innerHTML = wizardView(); if (ui.screen === 'trip') view.innerHTML = tripView(); nav(); }

function fleetsView() {
  if (ui.closingName) return `<section class="card close-animation"><div class="truck-finish">🚚</div><h2>Frota ${esc(ui.closingName)} fechada!</h2><p class="intro">A prestação foi enviada para o histórico.</p></section>`;
  if (ui.newFleet) return startFleetView();
  if (!state.active.length) return `<section class="card empty"><div class="truck-finish">🚚</div><h2>Minha Frota</h2><p class="intro">Abra uma frota para iniciar uma nova viagem.</p><button class="button" data-action="new-fleet">Abrir frota</button></section>`;
  const cards = state.active.map(record => `<article class="card fleet-open-card" role="button" tabindex="0" data-action="open-trip" data-id="${record.id}"><div class="fleet-card"><div><h2>🚚 Frota ${esc(record.fields.frota || 'sem número')}</h2><p>${esc(record.fields.motorista || 'Motorista não informado')} · Saída: ${dateText(record.fields.dataSaida)}</p><span class="badge">EM VIAGEM</span><p class="open-hint">Toque no cartão para registrar abastecimento ou gasto extra.</p></div><div class="fleet-actions"><button class="button danger" data-action="cancel-fleet" data-id="${record.id}">Cancelar</button></div></div></article>`).join('');
  return `<div class="section-title"><h2>Frota aberta</h2></div>${cards}`;
}
function startFleetView() { return `<div class="section-title"><h2>Abrir nova frota</h2>${state.active.length ? '<button class="button secondary" data-action="cancel-start">Voltar</button>' : ''}</div><section class="card"><p class="intro">Informe os dados de saída. Durante a viagem, você poderá acessar somente abastecimentos e gastos extras com rapidez.</p><div class="fields two"><label>Número da frota<input id="startFrota" inputmode="numeric" placeholder="Ex.: 123" /></label><label>Nome do motorista<input id="startMotorista" placeholder="Nome completo" /></label><label>Origem<input id="startOrigem" placeholder="Cidade de saída" /></label><label>Data de saída<input id="startData" type="date" /></label><label>KM de saída<input id="startKm" inputmode="decimal" placeholder="0" /></label></div><button class="button wide" style="margin-top:17px" data-action="open-fleet">Iniciar frota</button></section>`; }
function historyView() {
  const filtered = ui.historyFilter ? state.history.filter(item => item.closedAt.slice(0,10) === ui.historyFilter) : state.history.slice(0,10);
  const entries = filtered.map(item => `<article class="card fleet-card"><div><h2>Frota ${esc(item.fields.frota || 'sem número')}</h2><p>${esc(item.fields.motorista || 'Motorista não informado')} · Fechada em ${dateText(item.closedAt.slice(0,10))}</p><span class="badge">${brl(totals(item).net)}</span></div><button class="button secondary" data-action="history-pdf" data-id="${item.id}">Abrir PDF</button></article>`).join('');
  return `<div class="section-title"><h2>Histórico</h2></div><section class="card"><label class="history-filter">Pesquisar pela data de fechamento<input type="date" data-history-date value="${esc(ui.historyFilter)}" /></label><p class="small">Sem pesquisa, são mostradas as 10 últimas prestações. Escolha uma data para procurar as mais antigas.</p></section>${entries || `<section class="card empty"><h2>Nenhuma prestação encontrada</h2><p class="intro">As frotas fechadas aparecerão aqui.</p></section>`}`;
}
function accountView() { return `<section class="card"><div class="section-title"><h2>Conta</h2></div><p class="account-note">Estes dados aparecem no relatório PDF para identificar a empresa e o responsável.</p><div class="fields two" style="margin-top:16px"><label>Empresa<input data-account="empresa" value="${esc(state.account.empresa)}" placeholder="Nome da empresa" /></label><label>Responsável<input data-account="responsavel" value="${esc(state.account.responsavel)}" placeholder="Nome do responsável" /></label></div></section>`; }
function tripView() { const record=current(); if(!record){ui.screen='fleets';return fleetsView();} const isFuel=ui.tripTab==='fuel'; const content=isFuel?fuelView(record):extrasView(record); return `<section class="trip-title"><button class="back-link" data-action="back-fleets">‹ Frotas</button><h2>Frota ${esc(record.fields.frota)}</h2><p>${esc(record.fields.motorista)}</p></section><div class="folder-tabs"><button class="${isFuel?'active':''}" data-action="trip-tab" data-tab="fuel">⛽ Abastecimento</button><button class="${!isFuel?'active':''}" data-action="trip-tab" data-tab="extras">＋ Gastos extras</button></div><section class="card trip-content">${content}</section><button class="button wide trip-closed" data-action="finish-trip" data-id="${record.id}">Fechar viagem</button>`; }
function field(label, name, opts='') { const record=current(); return `<label>${label}<input name="${name}" data-field="${name}" value="${esc(record.fields[name])}" ${opts} /></label>`; }
function wizardView() {
  const record=current(); if (!record) { ui.screen='fleets'; return fleetsView(); }
  const step = ui.step, p = step/6*100;
  let content='';
  if (step === 1) content = `<div class="step-head"><span class="step-number">1</span><div><h2>Acerto do motorista</h2><p>Comece identificando a frota e o motorista.</p></div></div><div class="fields two">${field('Número da frota','frota','inputmode="numeric" placeholder="Ex.: 123"')}${field('Nome do motorista','motorista','placeholder="Nome completo"')}</div>`;
  if (step === 2) content = `<div class="step-head"><span class="step-number">2</span><div><h2>Dados de chegada</h2><p>Preencha somente depois que a viagem for encerrada.</p></div></div><div class="fields two">${field('Cidade de destino','cidadeDestino','placeholder="Cidade de chegada"')}${field('UF destino','ufDestino','maxlength="2" placeholder="SP"')}${field('Data de chegada','dataRetorno','type="date"')}${field('KM de chegada','kmChegada','inputmode="decimal" placeholder="0"')}${field('Adiantamento no cartão (R$)','adiantamentoCartao','data-currency inputmode="numeric" placeholder="0,00"')}${field('Adiantamento em dinheiro (R$)','adiantamentoDinheiro','data-currency inputmode="numeric" placeholder="0,00"')}${field('Valor do frete (R$)','valorFrete','data-currency inputmode="numeric" placeholder="0,00"')}</div>`;
  if (step === 3) content = fuelView(record);
  if (step === 4) content = extrasView(record);
  if (step === 5) content = closingView(record);
  if (step === 6) content = pdfView(record);
  const nextLabel = step === 1 ? 'OK' : step === 2 ? 'Fechar frota' : step === 3 ? 'Gastos extras' : step === 4 ? 'Viagem fechada' : step === 5 ? 'Confirmar e gerar PDF' : 'Próximo';
  const footer = step < 6 ? `<div class="step-nav"><button class="button secondary" data-action="wizard-back" ${step===1?'disabled':''}>Voltar</button><button class="button" data-action="wizard-next">${nextLabel}</button></div>` : '';
  return `<div class="progress"><span style="width:${p}%"></span></div><section class="card">${content}${footer}</section><button class="button danger wide" data-action="cancel-fleet" data-id="${record.id}">Cancelar esta frota</button>`;
}
function fuelView(record) { const rows=record.fueling.map((item,i)=>`<tr><td>${esc(item.local)}</td><td>${esc(item.km)}</td><td>${esc(item.liters)}</td><td>${brl(number(item.amount))}</td><td><button class="remove" data-action="remove-fuel" data-index="${i}">×</button></td></tr>`).join(''); return `<div class="step-head"><span class="step-number">3</span><div><h2>Abastecimentos</h2><p>Cadastre até 15 abastecimentos durante a viagem.</p></div></div><div class="entry fuel-entry"><label>Local<input id="fuelLocal" placeholder="Ex.: Posto Avenida" /></label><label>KM<input id="fuelKm" inputmode="decimal" placeholder="0" /></label><label>Litros<input id="fuelLiters" inputmode="decimal" placeholder="0,00" /></label><label>Valor pago (R$)<input id="fuelAmount" data-currency inputmode="numeric" placeholder="0,00" /></label><button class="button" data-action="add-fuel" ${record.fueling.length>=15?'disabled':''}>Adicionar abastecimento</button></div><p class="small">${record.fueling.length} de 15 abastecimentos cadastrados</p><div class="table-wrap"><table><thead><tr><th>Local</th><th>KM</th><th>Litros</th><th>Valor</th><th></th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td colspan="3">Total de abastecimento</td><td>${brl(totals(record).fuel)}</td><td></td></tr></tfoot></table></div>`; }
function extrasView(record) { const rows=record.extras.map((item,i)=>`<tr><td>${esc(item.name)}</td><td>${esc(item.payment)}</td><td>${brl(number(item.amount))}</td><td><button class="remove" data-action="remove-extra" data-index="${i}">×</button></td></tr>`).join(''); return `<div class="step-head"><span class="step-number">4</span><div><h2>Gastos extras</h2><p>Registre pedágio, alimentação e outros gastos.</p></div></div><div class="entry extra-entry"><label>Nome do gasto<input id="extraName" placeholder="Ex.: Pedágio" /></label><label>Pagamento<select id="extraPayment"><option>À vista</option><option>Crédito</option></select></label><label>Valor pago (R$)<input id="extraAmount" data-currency inputmode="numeric" placeholder="0,00" /></label><button class="button" data-action="add-extra">Adicionar gasto</button></div><div class="table-wrap"><table><thead><tr><th>Gasto</th><th>Pagamento</th><th>Valor</th><th></th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td colspan="2">Total de gastos extras</td><td>${brl(totals(record).extras)}</td><td></td></tr></tfoot></table></div>`; }
function summaryFields(record) { const f=record.fields, t=totals(record), km=Math.max(0,number(f.kmChegada)-number(f.kmSaida)); return `<div class="summary-grid"><div><span>Frota</span><strong>${esc(f.frota||'—')}</strong></div><div><span>Motorista</span><strong>${esc(f.motorista||'—')}</strong></div><div><span>Origem</span><strong>${esc(f.origem||'—')}</strong></div><div><span>Destino</span><strong>${esc(`${f.cidadeDestino}${f.ufDestino?' / '+f.ufDestino.toUpperCase():''}`||'—')}</strong></div><div><span>Quilometragem</span><strong>${km.toLocaleString('pt-BR')} km</strong></div><div><span>Abastecimentos (${record.fueling.length})</span><strong>${brl(t.fuel)}</strong></div><div><span>Gastos extras (${record.extras.length})</span><strong>${brl(t.extras)}</strong></div></div>`; }
function closingView(record) { const t=totals(record); return `<div class="step-head"><span class="step-number">5</span><div><h2>Resumo de fechamento</h2><p>Confira os valores antes de confirmar a prestação.</p></div></div>${summaryFields(record)}<div class="total-box"><span>Total de despesas</span><strong>${brl(t.expenses)}</strong></div><div class="total-box"><span>Saldo da prestação</span><strong>${brl(t.net)}</strong></div>`; }
function pdfView(record) { return `<div class="step-head"><span class="step-number">6</span><div><h2>Gerar relatório</h2><p>Inclua uma observação, se quiser, e gere o PDF para enviar.</p></div></div><label>Observação (opcional)<textarea data-field="observacao" rows="4" placeholder="Digite aqui, se necessário.">${esc(record.fields.observacao)}</textarea></label><button class="button wide" style="margin-top:16px" data-action="generate-pdf">Gerar PDF</button><div id="afterPdf" hidden><p class="close-message">Depois de salvar ou enviar o PDF, finalize a prestação para movê-la ao histórico.</p><button class="close-report" data-action="close-report">Fechamento da prestação</button></div>`; }

function newFleet() { ui={...ui,screen:'fleets',newFleet:true,closingName:''}; render(); }
function openNewFleet() { const frota=$('#startFrota').value.trim(), motorista=$('#startMotorista').value.trim(), origem=$('#startOrigem').value.trim(), dataSaida=$('#startData').value, kmSaida=$('#startKm').value; if(!frota||!motorista||!origem||!dataSaida||!kmSaida){alert('Preencha número da frota, motorista, origem, data e KM de saída.');return;} const fields=defaultFields(); Object.assign(fields,{frota,motorista,origem,dataSaida,kmSaida}); const record={id:createId(),fields,fueling:[],extras:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.active.unshift(record);save();ui={...ui,screen:'trip',currentId:record.id,tripTab:'fuel',newFleet:false};render(); }
function openFleet(id) { ui.screen='wizard'; ui.currentId=id; ui.step=1; render(); }
function openFleetAt(id, step) { ui.screen='wizard'; ui.currentId=id; ui.step=step; render(); }
function openTrip(id) { ui.screen='trip'; ui.currentId=id; ui.tripTab='fuel'; render(); }
function addFuel() { const record=current(), amount=$('#fuelAmount').value; if (!number(amount) || record.fueling.length>=15) { $('#fuelAmount').focus(); return; } record.fueling.push({local:$('#fuelLocal').value,km:$('#fuelKm').value,liters:$('#fuelLiters').value,amount}); touch(record); render(); }
function addExtra() { const record=current(), amount=$('#extraAmount').value; if (!number(amount)) { $('#extraAmount').focus(); return; } record.extras.push({name:$('#extraName').value,payment:$('#extraPayment').value,amount}); touch(record); render(); }
function validateStep() { const r=current(); if(ui.step===1 && (!r.fields.frota.trim() || !r.fields.motorista.trim())) { alert('Preencha o número da frota e o nome do motorista.'); return false; } return true; }
function nextWizard() { if(!validateStep()) return; const flow={1:3,2:5,3:4,4:2,5:6}; ui.step=flow[ui.step]||6; render(); }
function closeReport() { const record=current(); const name=record.fields.frota||'sem número'; record.closedAt=new Date().toISOString(); state.active=state.active.filter(item=>item.id!==record.id); state.history.unshift(record); save(); ui={...ui,screen:'fleets',currentId:null,step:1,newFleet:false,closingName:name}; render(); setTimeout(()=>{ui.closingName='';render();},1400); }
function cancelFleet(id) { const record = state.active.find(item => item.id === id); if (!record) return; const label = record.fields.frota ? `a frota ${record.fields.frota}` : 'esta frota'; if (!confirm(`Cancelar ${label}? Todos os dados preenchidos serão apagados e não irão para o histórico.`)) return; state.active = state.active.filter(item => item.id !== id); save(); ui = {...ui, screen:'fleets', currentId:null, step:1}; render(); }
function pdfLine(label,value){return `<div><span>${label}</span><strong>${esc(value)}</strong></div>`;}
function buildPdf(record) { const f=record.fields,t=totals(record),km=Math.max(0,number(f.kmChegada)-number(f.kmSaida)); $('#pdfReport').innerHTML=`<header><div><p class="pdf-kicker">${esc(state.account.empresa||'MINHA FROTA')}</p><h1>Acerto do Motorista</h1><p>Relatório financeiro de viagem</p></div><div class="pdf-date">Emitido em<br><strong>${new Date().toLocaleDateString('pt-BR')}</strong></div></header><section class="pdf-section"><h2>Identificação da viagem</h2><div class="pdf-grid">${pdfLine('Frota',f.frota)}${pdfLine('Motorista',f.motorista)}${pdfLine('Origem',f.origem)}${pdfLine('Destino',`${f.cidadeDestino||'Não informado'}${f.ufDestino?' / '+f.ufDestino.toUpperCase():''}`)}${pdfLine('Período',`${dateText(f.dataSaida)} a ${dateText(f.dataRetorno)}`)}${pdfLine('Quilometragem',`${km.toLocaleString('pt-BR')} km`)}</div></section><section class="pdf-section"><h2>Movimentação financeira</h2><div class="pdf-grid">${pdfLine('Valor do frete',brl(t.freight))}${pdfLine('Adiantamentos',brl(t.advances))}${pdfLine(`Abastecimentos (${record.fueling.length})`,brl(t.fuel))}${pdfLine(`Gastos extras (${record.extras.length})`,brl(t.extras))}</div></section><section class="pdf-section"><h2>Fechamento</h2><div class="pdf-total">${pdfLine('Total de despesas',brl(t.expenses))}${pdfLine('Saldo da prestação',brl(t.net))}</div></section>${f.observacao?`<section class="pdf-section"><h2>Observação</h2><p class="pdf-note">${esc(f.observacao)}</p></section>`:''}<footer>${state.account.responsavel?`Responsável: ${esc(state.account.responsavel)} · `:''}Documento gerado pelo aplicativo Minha Frota.</footer>`; window.print(); }

document.addEventListener('click', event => { const button=event.target.closest('[data-action],[data-nav]'); if(!button)return; if(button.dataset.nav){ui.screen=button.dataset.nav;ui.currentId=null;ui.newFleet=false;render();return;} const action=button.dataset.action; if(action==='new-fleet')newFleet(); if(action==='cancel-start'){ui.newFleet=false;render();} if(action==='open-fleet')openNewFleet(); if(action==='continue')openFleet(button.dataset.id); if(action==='open-trip')openTrip(button.dataset.id); if(action==='back-fleets'){ui.screen='fleets';ui.currentId=null;render();} if(action==='trip-tab'){ui.tripTab=button.dataset.tab;render();} if(action==='quick-fuel')openFleetAt(button.dataset.id,3); if(action==='quick-extra')openFleetAt(button.dataset.id,4); if(action==='finish-trip')openFleetAt(button.dataset.id,2); if(action==='cancel-fleet')cancelFleet(button.dataset.id); if(action==='wizard-back'){ui.step=Math.max(1,ui.step-1);render();} if(action==='wizard-next')nextWizard(); if(action==='add-fuel')addFuel(); if(action==='add-extra')addExtra(); if(action==='remove-fuel'){current().fueling.splice(Number(button.dataset.index),1);touch(current());render();} if(action==='remove-extra'){current().extras.splice(Number(button.dataset.index),1);touch(current());render();} if(action==='generate-pdf'){buildPdf(current());$('#afterPdf').hidden=false;} if(action==='close-report')closeReport(); if(action==='history-pdf'){const record=state.history.find(item=>item.id===button.dataset.id);buildPdf(record);} });
document.addEventListener('input', event => { const r=current(); if(event.target.matches('[data-currency]')) event.target.value=currencyMask(event.target.value); if(event.target.matches('[data-field]')&&r){r.fields[event.target.dataset.field]=event.target.value;touch(r);} if(event.target.matches('[data-account]')){state.account[event.target.dataset.account]=event.target.value;save();} if(event.target.matches('[data-history-date]')){ui.historyFilter=event.target.value;render();} });
document.addEventListener('keydown', event => { if(event.key!=='Enter'||event.target.tagName==='TEXTAREA'||!event.target.matches('input,select'))return; event.preventDefault(); if(ui.step===3&&event.target.id==='fuelAmount'){addFuel();return;} if(ui.step===4&&event.target.id==='extraAmount'){addExtra();return;} const inputs=[...document.querySelectorAll(`#view .card input, #view .card select`)].filter(input=>!input.disabled);const next=inputs[inputs.indexOf(event.target)+1];if(next)next.focus();else if(ui.screen==='wizard'&&ui.step<6)nextWizard(); });
render();
